"""
Annual Report Export Module

Handles generation of Word and PDF exports for the Annual Report feature.
Converts chart images and data into professionally formatted documents.

Author: Waqqas Hanafi
Copyright: © 2025 Calaveras County Health and Human Services Agency
"""

import base64
import io
import logging
import re
from typing import Dict, List
from datetime import datetime

# Document generation libraries
try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

logger = logging.getLogger(__name__)


def generate_word_report(report_data: Dict, username: str) -> io.BytesIO:
    """
    Generate Word document from annual report data
    
    Args:
        report_data: Dictionary containing report period, summary, charts, and performance data
        username: User who generated the report
        
    Returns:
        BytesIO object containing the Word document
    """
    if not DOCX_AVAILABLE:
        raise ImportError("python-docx not installed. Install with: pip install python-docx")
    
    doc = Document()
    
    # Add title
    title = doc.add_heading('Calaveras County HHSA', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    subtitle = doc.add_heading('Annual Report', level=1)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add report metadata
    doc.add_paragraph()
    metadata_table = doc.add_table(rows=3, cols=2)
    metadata_table.style = 'Light Grid Accent 1'
    
    metadata_table.rows[0].cells[0].text = 'Report Period:'
    metadata_table.rows[0].cells[1].text = report_data.get('period', '')
    metadata_table.rows[1].cells[0].text = 'Generated:'
    metadata_table.rows[1].cells[1].text = report_data.get('generated_date', '')
    metadata_table.rows[2].cells[0].text = 'Generated By:'
    metadata_table.rows[2].cells[1].text = username
    
    doc.add_page_break()
    
    # Executive Summary
    doc.add_heading('Executive Summary', level=1)
    
    summary = report_data.get('summary', {})
    summary_table = doc.add_table(rows=4, cols=2)
    summary_table.style = 'Light Grid Accent 1'
    summary_data = [
        ('Total Referrals', summary.get('total_referrals', '-')),
        ('Total Cases', summary.get('total_cases', '-')),
        ('Unique People Served', summary.get('total_people', '-')),
        ('Assistance Requests', summary.get('total_assistance', '-'))
    ]
    
    for idx, (label, value) in enumerate(summary_data):
        summary_table.rows[idx].cells[0].text = label
        summary_table.rows[idx].cells[1].text = value
        # Bold the values
        summary_table.rows[idx].cells[1].paragraphs[0].runs[0].font.bold = True
        summary_table.rows[idx].cells[1].paragraphs[0].runs[0].font.size = Pt(14)
    
    doc.add_page_break()
    
    # Service Overview
    doc.add_heading('Service Overview', level=1)
    
    charts = report_data.get('charts', {})
    chart_sections = [
        ('annualReferralStatusChart', 'Referral Status Distribution'),
        ('annualCaseStatusChart', 'Case Status Distribution'),
        ('annualServiceTypesChart', 'Top Service Types'),
        ('annualTimelineChart', 'Referrals Over Time')
    ]
    
    for chart_id, chart_title in chart_sections:
        if chart_id in charts:
            doc.add_heading(chart_title, level=2)
            _add_chart_image(doc, charts[chart_id], width=6.0)
            doc.add_paragraph()
    
    doc.add_page_break()
    
    # Demographics
    doc.add_heading('Client Demographics', level=1)
    
    demo_charts = [
        ('annualAgeChart', 'Age Distribution'),
        ('annualGenderChart', 'Gender Distribution'),
        ('annualRaceChart', 'Race/Ethnicity'),
        ('annualHouseholdChart', 'Household Size Distribution'),
        ('annualHouseholdScatterChart', 'Household Composition (Adults vs Children)'),
        ('annualIncomeChart', 'Income Distribution'),
        ('annualInsuranceChart', 'Insurance Coverage'),
        ('annualCommPrefChart', 'Communication Preferences'),
        ('annualMaritalChart', 'Marital Status'),
        ('annualLanguageChart', 'Language Preferences'),
        ('annualMilAffChart', 'Military Affiliation'),
        ('annualMilBranchChart', 'Military Branch Distribution')
    ]
    
    for chart_id, chart_title in demo_charts:
        if chart_id in charts:
            doc.add_heading(chart_title, level=2)
            _add_chart_image(doc, charts[chart_id], width=5.5)
            doc.add_paragraph()
    
    doc.add_page_break()
    
    # Network Collaboration
    doc.add_heading('Network Collaboration', level=1)
    
    network_charts = [
        ('annualSendingProvidersChart', 'Top Sending Providers'),
        ('annualReceivingProvidersChart', 'Top Receiving Providers'),
        ('annualTopProgramsChart', 'Top Programs by Referral Volume')
    ]
    
    for chart_id, chart_title in network_charts:
        if chart_id in charts:
            doc.add_heading(chart_title, level=2)
            _add_chart_image(doc, charts[chart_id], width=6.0)
            doc.add_paragraph()
    
    # Program Performance Table
    tables = report_data.get('tables')
    if tables is None:
        tables = {}
    program_performance = tables.get('program_performance', [])
    
    # Fallback to old structure for backward compatibility
    if not program_performance:
        program_performance = report_data.get('program_performance', [])
    
    if program_performance:
        doc.add_heading('Program Performance Metrics', level=2)
        
        perf_table = doc.add_table(rows=len(program_performance) + 1, cols=4)
        perf_table.style = 'Light Grid Accent 1'
        
        # Headers
        headers = ['Program Name', 'Total Referrals', 'Accepted', 'Acceptance Rate']
        for idx, header in enumerate(headers):
            cell = perf_table.rows[0].cells[idx]
            cell.text = header
            cell.paragraphs[0].runs[0].font.bold = True
        
        # Data rows
        for row_idx, program in enumerate(program_performance, start=1):
            perf_table.rows[row_idx].cells[0].text = program.get('program_name', '')
            perf_table.rows[row_idx].cells[1].text = program.get('total_referrals', '')
            perf_table.rows[row_idx].cells[2].text = program.get('accepted', '')
            perf_table.rows[row_idx].cells[3].text = program.get('acceptance_rate', '')
        
        doc.add_paragraph()
    
    doc.add_page_break()
    
    # Geographic Distribution
    doc.add_heading('Geographic Distribution', level=1)
    
    geo_charts = [
        ('annualCitiesChart', 'Top Cities Served'),
        ('annualCountiesChart', 'County Distribution')
    ]
    
    for chart_id, chart_title in geo_charts:
        if chart_id in charts:
            doc.add_heading(chart_title, level=2)
            _add_chart_image(doc, charts[chart_id], width=5.5)
            doc.add_paragraph()
    
    doc.add_page_break()
    
    # Service Outcomes
    doc.add_heading('Service Outcomes', level=1)
    
    outcome_charts = [
        ('annualCaseOutcomesChart', 'Case Outcomes by Resolution Type'),
        ('annualResolutionByServiceChart', 'Resolution Types by Service Category'),
        ('annualReferralFunnelChart', 'Service Referral Funnel'),
        ('annualJourneyStagesChart', 'Client Journey Stages')
    ]
    
    for chart_id, chart_title in outcome_charts:
        if chart_id in charts:
            doc.add_heading(chart_title, level=2)
            _add_chart_image(doc, charts[chart_id], width=5.5)
            doc.add_paragraph()
    
    # Add any remaining charts that weren't in the organized sections
    # Track which charts we've already added
    added_charts = set()
    for section in [chart_sections, demo_charts, network_charts, geo_charts, outcome_charts]:
        for chart_id, _ in section:
            if chart_id in charts:
                added_charts.add(chart_id)
    
    # Find charts that haven't been added yet
    remaining_charts = {k: v for k, v in charts.items() if k not in added_charts}
    
    if remaining_charts:
        doc.add_page_break()
        doc.add_heading('Additional Charts', level=1)
        
        for chart_id, chart_image in remaining_charts.items():
            # Generate a readable title from the chart ID
            # Remove 'annual' prefix and 'Chart' suffix, then format
            title = chart_id.replace('annual', '').replace('Chart', '')
            # Convert camelCase to Title Case
            title = re.sub(r'([A-Z])', r' \1', title).strip()
            title = title.replace('  ', ' ')
            if not title:
                title = chart_id
            
            doc.add_heading(title, level=2)
            _add_chart_image(doc, chart_image, width=5.5)
            doc.add_paragraph()
    
    # Save to BytesIO
    output = io.BytesIO()
    doc.save(output)
    output.seek(0)
    
    return output


def generate_pdf_report(report_data: Dict, username: str) -> io.BytesIO:
    """
    Generate PDF from annual report data
    
    Args:
        report_data: Dictionary containing report period, summary, charts, and performance data
        username: User who generated the report
        
    Returns:
        BytesIO object containing the PDF
    """
    if not REPORTLAB_AVAILABLE:
        raise ImportError("reportlab not installed. Install with: pip install reportlab")
    
    output = io.BytesIO()
    doc = SimpleDocTemplate(output, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#0066cc'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    # Add title
    story.append(Paragraph('Calaveras County HHSA', title_style))
    story.append(Paragraph('Annual Report', styles['Heading1']))
    story.append(Spacer(1, 0.3*inch))
    
    # Metadata table
    metadata_data = [
        ['Report Period:', report_data.get('period', '')],
        ['Generated:', report_data.get('generated_date', '')],
        ['Generated By:', username]
    ]
    metadata_table = Table(metadata_data, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.grey),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(metadata_table)
    story.append(Spacer(1, 0.5*inch))
    
    # Executive Summary
    story.append(Paragraph('Executive Summary', styles['Heading1']))
    story.append(Spacer(1, 0.2*inch))
    
    summary = report_data.get('summary', {})
    summary_data = [
        ['Metric', 'Value'],
        ['Total Referrals', summary.get('total_referrals', '-')],
        ['Total Cases', summary.get('total_cases', '-')],
        ['Unique People Served', summary.get('total_people', '-')],
        ['Assistance Requests', summary.get('total_assistance', '-')]
    ]
    summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (1, 1), (1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (1, 1), (1, -1), 14)
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.5*inch))
    
    # Add charts
    charts = report_data.get('charts', {})
    chart_sections = [
        ('Service Overview', [
            ('annualReferralStatusChart', 'Referral Status Distribution'),
            ('annualCaseStatusChart', 'Case Status Distribution'),
            ('annualServiceTypesChart', 'Top Service Types'),
            ('annualTimelineChart', 'Referrals Over Time')
        ]),
        ('Client Demographics', [
            ('annualAgeChart', 'Age Distribution'),
            ('annualGenderChart', 'Gender Distribution'),
            ('annualRaceChart', 'Race/Ethnicity'),
            ('annualHouseholdChart', 'Household Size Distribution'),
            ('annualHouseholdScatterChart', 'Household Composition'),
            ('annualIncomeChart', 'Income Distribution'),
            ('annualInsuranceChart', 'Insurance Coverage'),
            ('annualCommPrefChart', 'Communication Preferences'),
            ('annualMaritalChart', 'Marital Status'),
            ('annualLanguageChart', 'Language Preferences'),
            ('annualMilAffChart', 'Military Affiliation'),
            ('annualMilBranchChart', 'Military Branch Distribution')
        ]),
        ('Network Collaboration', [
            ('annualSendingProvidersChart', 'Top Sending Providers'),
            ('annualReceivingProvidersChart', 'Top Receiving Providers'),
            ('annualTopProgramsChart', 'Top Programs by Referral Volume')
        ]),
        ('Geographic Distribution', [
            ('annualCitiesChart', 'Top Cities Served'),
            ('annualCountiesChart', 'County Distribution')
        ]),
        ('Service Outcomes', [
            ('annualCaseOutcomesChart', 'Case Outcomes by Resolution Type'),
            ('annualResolutionByServiceChart', 'Resolution Types by Service'),
            ('annualReferralFunnelChart', 'Service Referral Funnel'),
            ('annualJourneyStagesChart', 'Client Journey Stages')
        ])
    ]
    
    for section_title, charts_list in chart_sections:
        story.append(Paragraph(section_title, styles['Heading1']))
        story.append(Spacer(1, 0.2*inch))
        
        for chart_id, chart_title in charts_list:
            if chart_id in charts:
                story.append(Paragraph(chart_title, styles['Heading2']))
                
                # Decode base64 image
                image_data = charts[chart_id].split(',')[1]  # Remove data:image/png;base64,
                image_bytes = base64.b64decode(image_data)
                image_stream = io.BytesIO(image_bytes)
                
                # Add image
                img = Image(image_stream, width=5.5*inch, height=3.5*inch)
                story.append(img)
                story.append(Spacer(1, 0.3*inch))
    
    # Program Performance Table
    tables = report_data.get('tables')
    if tables is None:
        tables = {}
    program_performance = tables.get('program_performance', [])
    
    # Fallback to old structure for backward compatibility
    if not program_performance:
        program_performance = report_data.get('program_performance', [])
    
    if program_performance:
        story.append(Paragraph('Program Performance Metrics', styles['Heading2']))
        story.append(Spacer(1, 0.2*inch))
        
        perf_data = [['Program Name', 'Total Referrals', 'Accepted', 'Acceptance Rate']]
        for program in program_performance[:10]:  # Top 10
            perf_data.append([
                program.get('program_name', ''),
                program.get('total_referrals', ''),
                program.get('accepted', ''),
                program.get('acceptance_rate', '')
            ])
        
        perf_table = Table(perf_data, colWidths=[2.5*inch, 1.2*inch, 1.2*inch, 1.2*inch])
        perf_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(perf_table)
    
    # Build PDF
    doc.build(story)
    output.seek(0)
    
    return output


def _add_chart_image(doc, base64_image: str, width: float = 6.0):
    """Helper to add chart image to Word document"""
    try:
        # Decode base64 image
        image_data = base64_image.split(',')[1] if ',' in base64_image else base64_image
        image_bytes = base64.b64decode(image_data)
        image_stream = io.BytesIO(image_bytes)
        
        # Add image to document
        doc.add_picture(image_stream, width=Inches(width))
        last_paragraph = doc.paragraphs[-1]
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    except Exception as e:
        logger.error(f"Failed to add chart image: {e}")
        doc.add_paragraph(f"[Chart image could not be embedded: {str(e)}]")
